### ISSUE TITLE
Simplify localized installations

### ISSUE THREAD

**Issue by mobab-th** [iped-docker/iped#9]
Hello,
I am not so familiar with Docker. But I tried to customize the IPED Dockerfile for language specific IPED installation. Attached the customized Dockerfile with settings for a German installation.

[Dockerfile-processor-DE.txt](https://github.com/iped-docker/iped/files/9992473/Dockerfile-processor-DE.txt)

**Comment by arisjr** [comment]
Hello, @mobab-th, 

I have not implemented yet multiple localization for OCR features indeed. But for the rest, I think you could use the default container as it is, using for example, the following command:

```
docker run --rm -it -e TZ="Europe/Berlin" -e iped_locale="de-DE" \
                 -e iped_enableOCR="true" -e iped_OCRLanguage="deu+frk" -e iped_phone_region="DE" \
                 -e iped_enableNamedEntityRecogniton="true" \
                 -e iped_enableAudioTranscription="true" \
                 -v /mnt/evidences:/evidences \
                 -v /mnt/ipedtmp:/mnt/ipedtmp \
                 -v /mnt/plugins:/mnt/plugins \
                 -v /mnt/hashesdb:/mnt/hashesdb \
                 -v /mnt/vosk_model:/root/IPED/iped/models/vosk/de-DE
                 -v /conf/YourNERConfig.txt:/root/IPED/iped/conf/NamedEntityRecognitionConfig.txt
                   ipeddocker/iped:processor java -jar iped.jar --nogui \
                 -d /evidences/test/test.dd \
                 -o /evidences/test/iped-output

```
EDITED: I have updated /mnt/hashesdb directory that was wrong on the example. 

As you can see, you can customize a bunch of IPED config variables just by setting environment variables (with the "iped_" prefix) on the container run, that entrypoint.sh will set them for you. At the end of the ipeddocker project page you can see all variables supported now. NER  config variables are not supported yet.

For the OCR features, I would implement the installation for all languages, but it would impose ~690MB of more size on the container. Instead of that, I will default install OCR languages for the IPED current supported languages, that is

Portuguese = tesseract-ocr-por
English = tesseract-ocr-eng
German = tesseract-ocr-deu tesseract-ocr-frk
Italian = tesseract-ocr-ita

For the NER models, after you download your preferred model, it should be inserted on the /mnt/plugins volume (only the additional plugins must be inserted here), that entrypoint.sh will do the rest. The NER config variables are still a work in progress, maybe in next release, so you must insert a configuration file as a volume, as  I done in the example.

For vosk models (and others), I would suggest you to use volumes, as I used above in the example.

I have a policy that I need to keep the container smaller as possible (it's already huge), so I will only insert the required applications in it - models, hash bases and such I try not to insert on the container, it must be added as a volume.

I will let this issue open until I correct the OCR languages on the Dockerfile-processor.

Any question on the matter, don't hesitate to ask.

**Comment by mobab-th** [comment]
Thank you for the hints. i will use it in the next case.

**Comment by arisjr** [comment]
- Added the IPED supported languages on tesseract OCR installation (por, eng, deu, frk, ita)
- Updated README.md about how to change the IPEDDOCKER locale

Changes have been made on 4.0.6_3 release (ipeddocker/iped:processor_4.0.6_3).

I will close this issue, if you have any other localization problem, please open another issue. 

Thanks for reporting. 
Regards
